### ISSUE TITLE
issue with fire style

### ISSUE THREAD

**Issue by raine** [sindresorhus/sparkly#11]
```
~ ❯❯❯ replem sparkly
Installed into REPL context:
 - sparkly@3.1.1 as sparkly
> sparkly([0, 0, 0], { style: 'fire' })
'NaN\u001b[0mNaN\u001b[0mNaN\u001b[0m'
> sparkly([0, 1, 0], { style: 'fire' })
'\u001b[38;5;230m▁\u001b[0m\u001b[38;5;196m█\u001b[0m\u001b[38;5;230m▁\u001b[0m'
> sparkly([0, 0, 0])
''
```

output with all zeroes is weird

**Comment by sindresorhus** [comment]
It seems this https://github.com/sindresorhus/sparkly/blob/233d6bf50160c0673435cab566434021e2872188/index.js#L28 returns `NaN` because it tries to divide `0` by `0`. I don't have the time to look into a solution right now, but PR welcome :)

**Comment by SamVerschueren** [comment]
What is the expected output if all are set to 0? All low ticks or just nothing?

**Comment by sindresorhus** [comment]
@SamVerschueren Lowest tick. Nothing means it's a gap caused by non-number value. See readme examples.
