### ISSUE TITLE
Windows CMD doesn't display sparklines, but missing character symbols instead

### ISSUE THREAD

**Issue by Tobsta** [sindresorhus/sparkly#13]

**Comment by SamVerschueren** [comment]
The symbols used are the [lower one eight block](http://www.fileformat.info/info/unicode/char/2581/index.htm) etc. The page I linked mentions `How to type in Microsoft Windows: Alt +2581`. I tested it and it renders well in Windows itself, but not in the CLI. Don't think we can solve this as there isn't a replacement for these symbols.

**Comment by sindresorhus** [comment]
Just use Bash for Windows.
