### ISSUE TITLE
`min`/`max` options

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sparkly#3]
To be able to do streaming sparklines.

https://github.com/holman/spark/pull/70

API:

```js
sparkly([10, 3, 5], {min: 1, max: 10});
```

CLI:

```
sparkly --min=1 --max=10 10 3 5
```

**Comment by sindresorhus** [comment]
// @asahaf in case you're interested in implementing this :)

**Comment by asahaf** [comment]
@sindresorhus I will do it :)
