### ISSUE TITLE
Extract cli to new repository

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/sparkly#5]
And tweak the cli a bit, like adding `meow`, etc.

**Comment by sindresorhus** [comment]
Hah, yeah, I was actually planning to when the open PR lands.

**Comment by sindresorhus** [comment]
Done https://github.com/sindresorhus/sparkly/commit/4a2e62a804b0ed842b218af21d538cf2d3fb8f5c

**Comment by SamVerschueren** [comment]
:+1: thanks
