### ISSUE TITLE
Colored sparks

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sparkly#8]
See https://github.com/holman/spark/pull/88.

**Comment by beatfreaker** [comment]
@sindresorhus what should be the color combination??

**Comment by sindresorhus** [comment]
@beatfreaker Same as in the referenced pull request.

**Comment by beatfreaker** [comment]
@sindresorhus any suggestion about how to use colors other than standard eight colors for example orange?

**Comment by sindresorhus** [comment]
Same as the referenced pull request. Use more than 8 colors. https://github.com/jbnicolai/ansi-256-colors
